version: '3'

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  openwrt:
    image: ghcr.io/home-assistant/addon-openwrt/aarch64:latest
    container_name: openwrt
    privileged: true
    network_mode: host
    volumes:
      - ./openwrt:/etc/openwrt
    restart: unless-stopped
