---
# System Management
- System:
    - Portainer:
        href: http://10.20.30.1:9000
        icon: portainer.png
        description: Container Management
        widget:
          type: portainer
          url: http://portainer:9000
          env: 2
          key: ptr_your_api_key_here

    - OpenWRT:
        href: http://10.20.30.1/cgi-bin/luci
        icon: openwrt.png
        description: Router & Network Control

    - System Monitor:
        href: http://10.20.30.1:3000/system
        icon: system-monitor.png
        description: Pi Resource Monitoring

# Media Services
- Media:
    - Jellyfin:
        href: http://10.20.30.1:8096
        icon: jellyfin.png
        description: Media Streaming Server
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: your_jellyfin_api_key_here

    - File Shares:
        href: smb://10.20.30.1
        icon: folder.png
        description: SMB/CIFS Network Shares

    - Downloads:
        href: http://10.20.30.1/downloads
        icon: download.png
        description: Download Manager (Future)

# Network Tools
- Network:
    - Wi-Fi Settings:
        href: http://10.20.30.1/cgi-bin/luci/admin/network/wireless
        icon: wifi.png
        description: Wireless Configuration

    - DHCP Clients:
        href: http://10.20.30.1/cgi-bin/luci/admin/status/overview
        icon: dhcp.png
        description: Connected Devices

# Tools & Utilities
- Tools:
    # Leave these commented until implemented
    # - Radio (SDR):
    #     href: http://10.20.30.1/radio
    #     icon: radio.png
    #     description: Software Defined Radio (Future)
    # - Wikipedia Offline:
    #     href: http://10.20.30.1/wikipedia
    #     icon: wikipedia.png
    #     description: Offline Wikipedia (Future)
    # - Maps Offline:
    #     href: http://10.20.30.1/maps
    #     icon: map.png
    #     description: Offline Maps (Future)
    # - E-Books:
    #     href: http://10.20.30.1/books
    #     icon: book.png
    #     description: Digital Library (Future)
