---
# System Management
- System:
    - Portainer:
        href: http://portainer.local:9000
        icon: portainer.png
        description: Container Management
        widget:
          type: portainer
          url: http://portainer:9000
          env: 2
          key: ptr_your_api_key_here

    - OpenWRT:
        href: http://10.20.30.1
        icon: openwrt.png
        description: Router & Network Control
        
    - Traefik:
        href: http://localhost:8080
        icon: traefik.png
        description: Reverse Proxy Dashboard

    - System Monitor:
        href: http://prepper-pi.local:3000/system
        icon: system-monitor.png
        description: Pi Resource Monitoring

# Media Services
- Media:
    - Jellyfin:
        href: http://jellyfin.local:8096
        icon: jellyfin.png
        description: Media Streaming Server
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: your_jellyfin_api_key_here

    - File Shares:
        href: \\10.20.30.40
        icon: folder.png
        description: SMB/CIFS Network Shares

    - Downloads:
        href: http://prepper-pi.local/downloads
        icon: download.png
        description: Download Manager

    - TV Tuner:
        href: http://prepper-pi.local/tv
        icon: tv.png
        description: OTA TV Tuning (Future)

# Network Tools
- Network:
    - Network Scanner:
        href: http://prepper-pi.local/network
        icon: network.png
        description: LAN Device Discovery

    - Wi-Fi Settings:
        href: http://10.20.30.1/cgi-bin/luci/admin/network/wireless
        icon: wifi.png
        description: Wireless Configuration

    - DHCP Clients:
        href: http://10.20.30.1/cgi-bin/luci/admin/status/overview
        icon: dhcp.png
        description: Connected Devices

    - Internet Test:
        href: http://prepper-pi.local/internet-test
        icon: speedtest.png
        description: Connectivity Check

# Tools & Utilities
- Tools:
    - Radio (SDR):
        href: http://prepper-pi.local/radio
        icon: radio.png
        description: Software Defined Radio (Future)

    - Wikipedia Offline:
        href: http://prepper-pi.local/wikipedia
        icon: wikipedia.png
        description: Offline Wikipedia (Future)

    - Maps Offline:
        href: http://prepper-pi.local/maps
        icon: map.png
        description: Offline Maps (Future)

    - E-Books:
        href: http://prepper-pi.local/books
        icon: book.png
        description: Digital Library (Future)
