---
# System Management
- System:
    - Portainer:
        href: http://10.20.30.40:9000
        icon: portainer.png
        description: Container Management
        widget:
          type: portainer
          url: http://portainer:9000
          env: 2
          key: ptr_your_api_key_here

    - OpenWRT:
        href: http://10.20.30.1
        icon: openwrt.png
        description: Router & Network Control
        
    # - Traefik:
    #     href: http://10.20.30.40:8080
    #     icon: traefik.png
    #     description: Reverse Proxy Dashboard

    - System Monitor:
        href: http://10.20.30.40:3000/system
        icon: system-monitor.png
        description: Pi Resource Monitoring

# Media Services
- Media:
    - Jellyfin:
        href: http://10.20.30.40:8096
        icon: jellyfin.png
        description: Media Streaming Server
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: your_jellyfin_api_key_here

    - File Shares:
        href: \\10.20.30.40
        icon: folder.png
        description: SMB/CIFS Network Shares

    - Downloads:
        href: http://10.20.30.40/downloads
        icon: download.png
        description: Download Manager (Future)

    # - TV Tuner:
    #     href: http://10.20.30.40/tv
    #     icon: tv.png
    #     description: OTA TV Tuning (Future)

# Network Tools
- Network:
    # - Network Scanner:
    #     href: http://10.20.30.40/network
    #     icon: network.png
    #     description: LAN Device Discovery

    - Wi-Fi Settings:
        href: http://10.20.30.1/cgi-bin/luci/admin/network/wireless
        icon: wifi.png
        description: Wireless Configuration

    - DHCP Clients:
        href: http://10.20.30.1/cgi-bin/luci/admin/status/overview
        icon: dhcp.png
        description: Connected Devices

    # - Internet Test:
    #     href: http://10.20.30.40/internet-test
    #     icon: speedtest.png
    #     description: Connectivity Check

# Tools & Utilities
- Tools:
    # - Radio (SDR):
    #     href: http://10.20.30.40/radio
    #     icon: radio.png
    #     description: Software Defined Radio (Future)

    # - Wikipedia Offline:
    #     href: http://10.20.30.40/wikipedia
    #     icon: wikipedia.png
    #     description: Offline Wikipedia (Future)

    # - Maps Offline:
    #     href: http://10.20.30.40/maps
    #     icon: map.png
    #     description: Offline Maps (Future)

    # - E-Books:
    #     href: http://10.20.30.40/books
    #     icon: book.png
    #     description: Digital Library (Future)
