---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/

title: Prepper Pi Dashboard
subtitle: Offline-First Raspberry Pi Server
favicon: https://github.com/pyrometheous/Prepper-Pi/raw/main/assets/favicon.ico

layout:
  System:
    style: row
    columns: 4
  Media:
    style: row
    columns: 4
  Network:
    style: row
    columns: 4
  Tools:
    style: row
    columns: 4
