---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/

title: Prepper Pi Dashboard
subtitle: Offline-First Raspberry Pi Server
# Use a local favicon if placed under homepage/icons/favicon.ico; otherwise comment this out
favicon: /app/config/icons/favicon.ico

layout:
  System:
    style: row
    columns: 4
  Media:
    style: row
    columns: 4
  Network:
    style: row
    columns: 4
  Tools:
    style: row
    columns: 4
