version: '3.8'

services:
  openwrt:
    # Use explicit ARM64 OpenWrt image for Raspberry Pi
    image: openwrt/rootfs:aarch64_generic-23.05.5
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./openwrt/config:/etc/config
      - ./openwrt/data:/root
      - ./openwrt/www:/www
      - ./openwrt/opennds:/etc/opennds
      - ./openwrt/bootstrap.sh:/root/bootstrap.sh:ro
      - /lib/firmware:/lib/firmware:ro
      - /sys/class/ieee80211:/sys/class/ieee80211:ro
      - /run/udev:/run/udev:ro
    command: ["/bin/sh", "-c", "/root/bootstrap.sh && /sbin/init"]
